kind: Template
apiVersion: v1
metadata:
  name: monero-xmrig
  labels:
    app: xmrig
objects:
#------------------------------------------------------------------------------#
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: miner-sa
#------------------------------------------------------------------------------#
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: monero-xmrig
    labels:
      app: xmrig
  spec:
    strategy:
      type: Rolling
    triggers:
    - type: ConfigChange
    replicas: 1
    selector:
      name: monero-xmrig
    template:
      metadata:
        labels:
          name: monero-xmrig
      spec:
        containers:
        - name: monero-xmrig
          image: quay.io/rblaine95/monero_xmrig
          imagePullPolicy: Always
          env:
          - name: username
            value: ${USER}
          - name: password
            value: ${PASS}
          - name: xmrpool
            value: ${XMR_POOL}
          - name: numthreads
            value: ${THREADS}
          - name: donate
            value: ${DONATE}
          - name: startport
            value: ${PORT}
        serviceAccount: miner-sa # oc adm policy add-scc-to-user anyuid -z miner-sa
#------------------------------------------------------------------------------#
parameters:
- name: USER
  displayName: Username
  description: Mining pool username
  required: true
- name: PASS
  displayName: Password
  description: Password for mining (x)
  required: false
  value: "x"
- name: XMR_POOL
  displayName: XMR Pool
  description: Pool to mine at
  required: false
  value: "xmr-usa.dwarfpool.com"
- name: THREADS
  displayName: Number of Threads
  description: Number of threads to mine with (L3/2048)
  required: false
- name: DONATE
  displayName: Donate percentage (0)
  required: false
  value: "0"
- name: PORT
  displayName: Start Port
  description: Port to start mining at
  required: false
  value: "8100"
